llm_provider: "openai" # Options: openai, llama3, anthropic, cohere, mistral
mode: "light" # Options: full, light

prompt: "v3" # Prompt to use from prompts.yaml
data_path: "data/processed/ground_truth_sample100.csv" # Path to the data file (YAML or CSV)

store_results: true
results_dir: "runs"
test_name: "v3_subsampleGroundTruth_openai" # convention: <version_of_prompt>_<data>_<model_name>
