llm_provider: "openai" # Options: openai, llama3, anthropic, cohere, mistral
mode: "light" # Options: full, light

prompt: "v3" # Prompt to use from prompts.yaml
data_path: "data/processed/ground_truth_synthetic.xlsx" # Path to the data file (YAML, CSV or XLSX)

store_results: true
results_dir: "runs"
test_name: "v3_GroundTruthSynthetic_openai" # convention: <version_of_prompt>_<data>_<model_name>
