# Stanford OpenIE Configuration

# Path to the data file containing texts to process
data_path: "data/raw/sample_for_openie.yaml"

# Base name for the batch processing output files
batch_name: "financial_sentences"

# Properties for Stanford OpenIE
# See https://stanfordnlp.github.io/CoreNLP/openie.html#api for more details
openie_properties:
  # Required annotators for OpenIE to work properly
  #annotators: "tokenize,pos,lemma,depparse,natlog,coref,openie"

  # Default value of openie.affinity_probability_cap is 1/3
  # Higher values will extract more triples but may be less accurate
  openie.affinity_probability_cap: 0.6667 # 2/3

  # Maximum number of clauses per sentence
  # Higher values will extract more triples but may be slower
  #openie.max_clauses_per_sentence: 10

  # Whether to resolve coreferences
  # This can improve the quality of extractions but may be slower
  #openie.resolve_coref: true

# Output directory for extracted triples
output_directory: "data/ground_truth/financial_sentences"

# Whether to generate visualization graphs
generate_graphs: true

# Batch processing settings
batch_processing:
  # Maximum number of texts to process in a single batch
  max_batch_size: 100

  # Whether to process texts in parallel
  parallel_processing: false

  # Number of parallel workers (if parallel_processing is true)
  num_workers: 4
