# Path to the data file containing texts to process
data_path: "data/raw/sample_news.yaml"
# Output settings
output:
  base_dir: "data/ground_truth"
  test_name: "sample_news" # or "sample_sentences"
  store_results: true


# Properties for Stanford OpenIE - See https://stanfordnlp.github.io/CoreNLP/openie.html#api for more details
openie_properties:
  #  Higher values will extract more triples but may be less accurate
  openie.affinity_probability_cap: 0.6667 # 2/3

  # Higher values will extract more triples but may be slower
  #openie.max_clauses_per_sentence: 10

  # Whether to resolve coreferences - This can improve the quality of extractions but may be slower
  #openie.resolve_coref: true

# Whether to generate visualization graphs
generate_graphs: true