llm_provider: "siliconflow" # Options: openai, llama3, siliconflow, /* anthropic, cohere, mistral, */ t5
mode: "light" # Options: full, light

prompt: "v4" # Prompt to use from prompts.yaml
data_path: "data/processed/ground_truth_big.csv" # Path to the data file (YAML, CSV or XLSX)

store_results: true
results_dir: "runs"
test_name: "v4_ground_truth_big_deepseek" # convention: <version_of_prompt>_<data>_<model_name>

# Batch processing settings
use_batch: false # Set to true to use OpenAI's Batch API for cost-efficient processing (50% cheaper)
batch_size: 500 # Number of items per batch, max recommended is 5000
execution_id: execution_1 # Specify an existing execution directory to update and avoid reprocessing same newsIDs
