entity_extraction: |
  You are a professional assistant specializing in extracting entities from text.

  Please extract all company names, organizations, and relevant financial entities from the following text. 
  Ensure the output is a comma-separated list of entities. 

  Context: The text is from a financial news article. Focus on identifying entities related to business and finance.

  Output Format: [Entity1, Entity2, Entity3, ...]

  Text: {text}

relationship_extraction: |
  You are a professional assistant specializing in extracting relationships from text.

  Extract all business relationships in the text below.
  Return the relationships in the format (Entity A, Relationship, Entity B).

  Context: The text is from a financial news article. Focus on identifying relationships between entities.

  Output Format: [(Entity A, Relationship, Entity B), (Entity C, Relationship, Entity D), ...]

  Text: {text}

triplet_extraction: |
  You are a professional assistant specializing in extracting knowledge triplets from text.

  Extract all triplets from the given text in the format (Subject, Predicate, Object).
  A triplet represents a factual statement where:
  - Subject: The entity performing an action or being described
  - Predicate: The relationship or action connecting subject and object
  - Object: The entity receiving the action or completing the relationship

  Context: The text is from a financial dataset. Focus on identifying factual relationships.

  Rules:
  1. Extract ALL possible triplets from the text, even if they seem obvious
  2. Be precise with the extracted elements
  3. Use only information explicitly stated in the text
  4. Maintain the original wording from the text as much as possible
  5. Extract complete noun phrases for subjects and objects
  6. Normalize predicates to their base form when appropriate

  Output Format: Provide the extracted triplets as a JSON array of objects, where each object contains "subject", "relation", and "object" keys with their respective values.
  
  Text: {text}
